#
# Azure Pipelines
#

trigger:
  - develop

pool:
  vmImage: ubuntu-latest

variables:
  npm_config_cache: "$(Pipeline.Workspace)/.npm"

steps:
  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: "18.x"

  - task: Cache@2
    displayName: Cache npm
    inputs:
      key: npm | "$(Agent.OS)" | package-lock.json
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(npm_config_cache)

  - script: npm ci
    displayName: Install dependencies

  - script: npm run build:assets
    displayName: Build assets

  - script: npm run lint
    displayName: Lint

  - script: npm run format:check
    displayName: Check format

  - script: npm run test:ci
    displayName: Test

  - task: PublishTestResults@2
    displayName: Publish test results
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: "**/test-results.xml"

  - task: PublishCodeCoverageResults@1
    displayName: Publish code coverage results
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "**/*coverage.xml"

  - script: npm run test:readme
    displayName: Test usage examples from README.md
